### ISSUE TITLE
actions/upload-artifact@v2

### ISSUE THREAD

**Issue by tabeatheunicorn** [nerdyscout/kicad-exports#14]
Tried your example file and got an error when it came to downloading action/upload-artifact@v2.0

**To Reproduce**
Just try your example file

**Expected behavior**
Downloading the needed github action

I did some reading on the marketplace and this version of the action does not exist. It works if you specify @v2 though. Minor bug but as everything else works (it took me some time to understand that I have to provide the kiplot.yaml file) I hope more people use your action!

**Comment by nerdyscout** [comment]
you are right, i changed the version tag.
thank you for making me aware of it.
