### ISSUE TITLE
Per-release diffing

### ISSUE THREAD

**Issue by brainstorm** [nerdyscout/kicad-exports#4]
It would be **awesome** to have diffs as part of the resulting upload/artifact bundle:

https://github.com/Gasman2014/KiCad-Diff

/cc @joshajohnson

**Comment by nerdyscout** [comment]
thanks for your suggestion.
actually I already implemented this a few days ago... it will be part of the upcoming v1.1. I just updated the development branch, so you could have a look at it if you like.

**Comment by brainstorm** [comment]
Looks great, looking forward to having 1.1 out and defining on my GHA workflows :D
